version: "3.8"
services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - ./.db.env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./.db.env
    # environment:
    #   PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #   PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  database:
