import type { Metadata } from "next";
import "./globals.css";
import { inter } from '@/styles/fonts'
import Header from "@/_components/sectionComponents/Header";
import Footer from "@/_components/sectionComponents/Footer";

export const metadata: Metadata = {
  title: "DevstockShop",
  description: "Generated by create next app",
  authors: [{ name: "Krzysztof Kozłowski" }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`} >
        <Header></Header>
        <main>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
