import type { Metadata } from "next";
import "./globals.css";
import { inter } from '@/styles/fonts'
import Header from "@/_components/sectionComponents/Header";
import Footer from "@/_components/sectionComponents/Footer";
import NextAuthSessionProvider from "@/_components/wrappers/NextAuthSessionProvider";

export const metadata: Metadata = {
  title: "DevstockShop",
  description: "Generated by create next app",
  authors: [{ name: "Krzysztof Kozłowski" }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`} >
        <NextAuthSessionProvider>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </NextAuthSessionProvider>
      </body>
    </html >
  );
}
