import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "DevStockShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <Header />
      <div className="bg-mainBg flex flex-col items-start gap-1 p-[40px]">
        {children}
      </div>
      <Footer />
    </ body>
  );
}
