import Footer from "@/components/sectionComponents/Footer";
import Header from "@/components/sectionComponents/Header";
import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "DevStockShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </ body>
  );
}
