import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "DevstockShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="bg-mainBg flex flex-col items-start h-screen">
        {children}
      </div>
  );
}
